Coverage
IslasGECI/irekua-database pull request #5
Opened 2021-06-24 19:19 UTC by nepito

2021-06-24 19:57 UTC, evaristor commented
@nepito ¿Por favor le podrías echar un 👀 ?

2021-07-01 18:08 UTC, evaristor requested changes
Actualmente, estamo evaluando cobertura sólamente en `irekua_geo`. Ahora debemos generalizarlo.

2021-07-22 18:33 UTC, islasfernando commented
Según yo [aquí](https://app.codecov.io/gh/CONABIO-audio/irekua-database/branch/master) se aprecia la covertura de todos los archivos, entonces ya esta?

2021-07-22 18:51 UTC, islasfernando approved these changes
LGTM 🆗

2021-07-22 18:52 UTC, merged

2021-07-22 19:08 UTC, devarops commented on Makefile
> +module = irekua_geo
@MaritzaB @islasfernando @xwalls ¿Sólo dejaron el módulo `irekua_geo`?